[package]
name = "day_13"
version = "0.1.0"
authors = ["jfrsmith"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.intcode]
path = "../intcode"

[dependencies]
console = "0.9.1"